package com.company.project.model;

public class Dept {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept.deptno
     *
     * @mbg.generated Wed Nov 28 23:09:12 CST 2018
     */
    private String deptno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept.dname
     *
     * @mbg.generated Wed Nov 28 23:09:12 CST 2018
     */
    private String dname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept.db_source
     *
     * @mbg.generated Wed Nov 28 23:09:12 CST 2018
     */
    private String dbSource;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept.deptno
     *
     * @return the value of dept.deptno
     *
     * @mbg.generated Wed Nov 28 23:09:12 CST 2018
     */
    public String getDeptno() {
        return deptno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept.deptno
     *
     * @param deptno the value for dept.deptno
     *
     * @mbg.generated Wed Nov 28 23:09:12 CST 2018
     */
    public void setDeptno(String deptno) {
        this.deptno = deptno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept.dname
     *
     * @return the value of dept.dname
     *
     * @mbg.generated Wed Nov 28 23:09:12 CST 2018
     */
    public String getDname() {
        return dname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept.dname
     *
     * @param dname the value for dept.dname
     *
     * @mbg.generated Wed Nov 28 23:09:12 CST 2018
     */
    public void setDname(String dname) {
        this.dname = dname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept.db_source
     *
     * @return the value of dept.db_source
     *
     * @mbg.generated Wed Nov 28 23:09:12 CST 2018
     */
    public String getDbSource() {
        return dbSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept.db_source
     *
     * @param dbSource the value for dept.db_source
     *
     * @mbg.generated Wed Nov 28 23:09:12 CST 2018
     */
    public void setDbSource(String dbSource) {
        this.dbSource = dbSource;
    }
}