package com.company.project.core;

import org.apache.ibatis.exceptions.TooManyResultsException;

import java.util.List;

/**
 * Service 层 基础接口，其他Service 接口 请继承该接口
 */
public interface Service<T> {
    int deleteById(String id);
    int save(T record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Thu Sep 06 23:01:02 CST 2018
     */
    T findById(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Thu Sep 06 23:01:02 CST 2018
     */
    List<T> findAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Thu Sep 06 23:01:02 CST 2018
     */
    int update(T record);
}
